### ISSUE TITLE
Docker install not working

### ISSUE THREAD

**Issue by domneedham** [nymanjens/facto#2]
I am trying to install using docker (following the steps in the README).

The image pulls okay but when completing the DB drop, encountering an error "standard_init_linux.go:219: exec user process caused: exec format error".

Any help appreciated :)

**Comment by nymanjens** [comment]
Hmm, I tried to reproduce this, but I got a different error instead:

>  The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

I don't really understand what the problem here is, especially as it used to work fine.

**Comment by domneedham** [comment]
Sorry, probably would have been useful to say I was attempting to run a Raspberry Pi 4. Seems to be an issue when the architecture is different (I'm not very experienced with Docker so not 100% on that)

**Comment by nymanjens** [comment]
If you are (like me) not very experienced with Docker, I would recommend using the binary release ("Installation from release
") instead of the Docker installation

**Comment by laymonage** [comment]
@nymanjens

Hi, I also encountered the database connection issue and was able to fix it by appending  `&disableMariaDbDriver` to the `DATABASE_URL`, so it becomes:

```yaml
DATABASE_URL: jdbc:mysql://db:3306/facto?user=root&password=facto&disableMariaDbDriver
```

It seems that MariaDB has its own JDBC driver now, and it may conflict with MySQL's or something. https://mariadb.com/kb/en/about-mariadb-connector-j/#having-mariadb-and-mysql-drivers-in-the-same-classpath

This may not be the ideal fix. Maybe you can try changing the connection string to use `jdbc:mariadb://` and use MariaDB's own JDBC driver in the application configuration. Hope this helps!

**Comment by nymanjens** [comment]
Thanks @laymonage! I added `disableMariaDbDriver` and I also found why my setup wasn't working --> the database hadn't started yet. I added a sleep to fix this.

So now if I run the commands in the README, everything seems to work.
