### ISSUE TITLE
How would I create a systemctl service for this?

### ISSUE THREAD

**Issue by aashishvasu** [nymanjens/facto#9]
I've managed to set up facto correctly, and even did a test run which worked. I do want to create a service for this so that it can auto launch. Here is the service:

```desktop
[Unit]
Description=Facto service
Documentation=https://github.com/nymanjens/facto

Wants=syslog.service

[Service]
Restart=always
User=ubuntu
WorkingDirectory=/home/ubuntu/facto
ExecStart=/home/ubuntu/facto/bin/server


[Install]
WantedBy=multi-user.target
```

When I run this, I get the following error (obtained using journalctl -u facto -b):
`[error] application - Error when parsing accounting-config.yml: java.io.FileNotFoundException: conf/accounting-config.yml`

It seems to me that it is running the server from a different directory, where it cant find the `conf` directory.

Any thoughts?

**Comment by nymanjens** [comment]
Hi Aashish,

This is the way I've been able to install this in unix: https://github.com/nymanjens/facto/blob/master/unix-service.sh

Your configuration looks correct. I'd guess that `accounting-config.yml` is misspelled, not there, or that `WorkingDirectory` is not picked up or so.

**Comment by aashishvasu** [comment]
Hi Jens,

I've used that unix service you created and made a systemd service from it, which seems to do the trick! Here it is:

```desktop
[Unit]
Description=Facto service
Documentation=https://github.com/nymanjens/facto

After=network.target

[Service]
User=root
WorkingDirectory=/path/to/facto
ExecStart=/bin/sh -c "cd /path/to/facto && bin/server > /tmp/facto-logs 2>&1"
KillSignal=SIGINT
PIDFile=/path/to/facto/RUNNING_PID
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```
